version: '3'

services:

  rabbitmq1:
    image: rabbit:latest
    hostname: rabbitmq1
    environment: 
      MASTER: 'true'
    networks:
      - rabbit-network
    healthcheck:
      test: [ "CMD-SHELL", "rabbitmq-diagnostics -q ping" ]
      interval: 10s
      timeout: 10s
      retries: 10

  rabbitmq2:
    restart: always
    image: rabbit:latest
    hostname: rabbitmq2
    networks:
      - rabbit-network
    depends_on:
      rabbitmq1:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "rabbitmq-diagnostics -q ping" ]
      interval: 10s
      timeout: 10s
      retries: 5

  rabbitmq3:
    restart: always
    image: rabbit:latest
    hostname: rabbitmq3
    networks:
      - rabbit-network
    depends_on:
      rabbitmq1:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "rabbitmq-diagnostics -q ping" ]
      interval: 10s
      timeout: 10s
      retries: 5
    
  haproxy:
    restart: always
    image: haproxy:1.7
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      rabbitmq1:
        condition: service_healthy
      rabbitmq2:
        condition: service_healthy
      rabbitmq3:
        condition: service_healthy
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - rabbit-network

networks:
  rabbit-network:
